# Generated by Django 5.2.1 on 2025-06-13 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_topicblog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topicblog',
            old_name='blogpost',
            new_name='title',
        ),
    ]
