# Generated by Django 5.2.1 on 2025-06-13 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_rename_blogpost_topicblog_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topicblog',
            old_name='title',
            new_name='text',
        ),
    ]
