# Generated by Django 5.2.1 on 2025-06-13 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_rename_title_topicblog_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topicblog',
            old_name='text',
            new_name='title',
        ),
    ]
